language: java
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      # Getting compile errors on javac 1.8.0_31-b13
      - oracle-java8-installer

install: true
script: mvn -B verify
cache:
  directories:
    - $HOME/.m2
branches:
  except:
  - /^release\/.*$/
